# Generated by Django 5.2.1 on 2025-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='seats_available',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seats_booked',
        ),
        migrations.AddField(
            model_name='bus',
            name='seats',
            field=models.JSONField(default=dict),
        ),
    ]
